FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
# Remplace npm ci par npm install
RUN npm install --no-audit --progress=false
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
