spring:
  application:
    name: trouvetonmatch
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trouve_ton_match?currentSchema=public
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
jwt:
   secret: 7A25432A462D4A614E645267556B58703273357638792F423F4528482B4B6250
   expiration: 86400000