INSERT INTO role (nom) VALUES ('Administrateur général'), ('Administrateur départemental'), ('Porteur'), ('Parrain');
INSERT INTO plateforme_initiative (nom) VALUES ('Nouvelle Aquitaine'), ('Charente'), ('Charente-Maritime'), ('Corrèze'), ('Creuse'), ('Dordogne'), ('Gironde'), ('Landes'), ('Lot-et-Garonne'), ('Pyrénées-Atlantiques'), ('Deux-Sèvres'), ('Vienne'), ('Haute-Vienne');
INSERT INTO lieu (departement, nom) VALUES ('79', 'Bressuire'), ('79', 'Celles-sur-Belle'), ('79', 'Cerizay'), ('79', 'La Gâtine'), ('79', 'Melle'), ('79', 'Mauléon'), ('79', 'Niort'), ('79', 'Parthenay'), ('79', 'Saint-Maixent-l''Ecole'), ('79', 'Thouars'), ('79', 'Le Val de Thouet');
INSERT INTO accompagnement (nom) VALUES ('Ressources humaines'), ('Finance / Comptabilité'), ('Juridique'), ('Informatique'), ('Commercial / Communication');
INSERT INTO domaine_activite (nom) VALUES ('Activités de services administratifs et de soutien'), ('Activités spécialisées, scientifiques et techniques'), ('Agriculture, sylviculture, pêche'), ('Arts, spectacles et activités récréatives'), ('Commerce et réparation'), ('Construction-BTP'), ('Enseignement'), ('Hôtels, cafés et restaurants'), ('Industrie'), ('Information et communication'), ('Production et distribution d’eau, assainissement, gestion des déchets et dépollution'), ('Production et distribution d’électricité, de gaz, de vapeur d’air conditionné'), ('Santé humaine et action sociale'), ('Services aux entreprises'), ('Services aux particuliers'), ('Transports');
INSERT INTO admin (nom_utilisateur, mail,nom, prenom, entreprise, plateforme_initiative_id, role_id) VALUES ('admin','admin@oli.com','ADMIN','Admin','Maif',1,1);
INSERT INTO membre (nom_utilisateur, mail,nom, prenom, entreprise, plateforme_initiative_id, role_id, actif) VALUES ('porteur avec details','port1@oli.com','PORTER DETAILS','porteur details','Roule tonton',1,3, true);
INSERT INTO membre (nom_utilisateur, mail,nom, prenom, entreprise, plateforme_initiative_id, role_id, actif) VALUES ('porteur sans details','port2@oli.com','PORTER','poaze','Roule',1,3, false);
INSERT INTO membre (nom_utilisateur, mail,nom, prenom, entreprise, plateforme_initiative_id, role_id, actif, description) VALUES ('El padre','elpadre@oli.com','BRANDO','Marlon','Mafia Niortaise',1,4, true, 'J''ai commencé au bas de l''échelle, en effectuant des tâches subalternes comme le recouvrement de dettes et la gestion de petites opérations. Grâce à ma loyauté et à mon efficacité, j''ai rapidement gagné la confiance de mes supérieurs. En gravissant les échelons, j''ai pris en charge des opérations plus importantes, telles que le trafic de drogue, le blanchiment d''argent et la corruption. Finalement, j''ai atteint le sommet de la hiérarchie. Aujourd''hui, je dirige des activités criminelles à grande échelle et prends des décisions stratégiques pour l''organisation. Mon parcours a été marqué par la violence, les trahisons et les luttes de pouvoir, mais c''est ainsi que j''ai forgé mon empire.');
INSERT INTO membre (nom_utilisateur, mail,nom, prenom, entreprise, plateforme_initiative_id, role_id, actif) VALUES ('La terreur','parai2n@oli.com','PACINO','Al','Mafia Gatinaise',1,4, true);
INSERT INTO membre (nom_utilisateur, mail,nom, prenom, entreprise, plateforme_initiative_id, role_id, actif) VALUES ('parain avec details 3','parai3n@oli.com','PARRAINNN','pépépé','Pegres',1,4, true);
INSERT INTO membre_lieu (membre_id, lieu_id) VALUES ('1','1'),('1','2'),('3','3'),('3','4'),('3','1'),('4','2'),('4','3'),('5','4'),(3,5),(3,6),(3,7),(3,8),(3,9),(3,10),(3,11);
INSERT INTO membre_accompagnement (membre_id, accompagnement_id) VALUES ('1','1'),('1','2'),('3','1'),('3','2'),('3','3'),('4','2'),('4','1'),('5','2'),('3','4'),('3','5');
INSERT INTO membre_domaine_activite (membre_id, domaine_activite_id) VALUES ('1','1'),('1','2'),('3','1'),('3','2'),('3','3'),('3','4'),('4','2'),('4','1'),('5','2'),('3','5'),('3','6'),('3','7'),('3','8'),('3','9'),('3','10'),('3','11'),('3','12'),('3','13'),('3','14'),('3','15'),('3','16');
-- ajout plus de detail sur membre
